version: '3.8'

services:

  # Frontend
  react_boilerplate:
    build: .
    container_name: react_boilerplate
    restart: always
    env_file:
      - .env
    ports:
      - "5173:5173"
    networks:
      - fastapi-network
    volumes:
      - ./:/app      
      - /app/node_modules

# Networks
networks:
  fastapi-network:
    name: my-fastapi-network

